# action.yml
name: "Wait on check"
author: "progapandist"
description: "Wait on a certain check to pass for commit"
inputs:
  ref:
    description: "A git ref to be checked: branch/tag/commit sha"
    required: true
  check-name:
    description: "A name of a check that has to pass"
    required: true
  repo-token:
    description: "A GitHub token for the repo"
    required: true
  wait-interval:
    description: "Seconds to wait between Checks API requests"
    required: true
    default: "10"
  repo:
    description: "Repository name"
    required: false
  owner: 
    description: "Owner of the repo"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.ref }}
    - ${{ inputs.check-name }}
    - ${{ inputs.repo-token }}
    - ${{ inputs.wait-interval }}
    - ${{ inputs.repo }}
    - ${{ inputs.owner }}
branding:
  icon: "check-circle"
  color: "green"
